package com.app.abckids;

public class ResourcePool {
    public static String DRAWING_ALPHABET = "alphabet";
    public static String ICON1 = "icon1";
    public static String ICON2 = "icon2";
    public static String ICON3 = "icon3";
    public static String ICON4 = "icon4";
    public static String ICON5 = "icon5";
    public static String ICON6 = "icon6";
    public static String NUMBER = "number";
    Integer[] alphabetSound = new Integer[]{Integer.valueOf(R.raw.a), Integer.valueOf(R.raw.b), Integer.valueOf(R.raw.c), Integer.valueOf(R.raw.d), Integer.valueOf(R.raw.e), Integer.valueOf(R.raw.f), Integer.valueOf(R.raw.g), Integer.valueOf(R.raw.h), Integer.valueOf(R.raw.i), Integer.valueOf(R.raw.j), Integer.valueOf(R.raw.k), Integer.valueOf(R.raw.l), Integer.valueOf(R.raw.m), Integer.valueOf(R.raw.n), Integer.valueOf(R.raw.o), Integer.valueOf(R.raw.p), Integer.valueOf(R.raw.q), Integer.valueOf(R.raw.r), Integer.valueOf(R.raw.s), Integer.valueOf(R.raw.t), Integer.valueOf(R.raw.u), Integer.valueOf(R.raw.v), Integer.valueOf(R.raw.w), Integer.valueOf(R.raw.x), Integer.valueOf(R.raw.y), Integer.valueOf(R.raw.z), Integer.valueOf(R.raw.yahh_abc)};
    Integer[] capitalStoke = new Integer[]{Integer.valueOf(R.drawable.e1), Integer.valueOf(R.drawable.e2), Integer.valueOf(R.drawable.e3), Integer.valueOf(R.drawable.e4), Integer.valueOf(R.drawable.e5), Integer.valueOf(R.drawable.e6), Integer.valueOf(R.drawable.e7), Integer.valueOf(R.drawable.e8), Integer.valueOf(R.drawable.e9), Integer.valueOf(R.drawable.e10), Integer.valueOf(R.drawable.e11), Integer.valueOf(R.drawable.e12), Integer.valueOf(R.drawable.e13), Integer.valueOf(R.drawable.e14), Integer.valueOf(R.drawable.e15), Integer.valueOf(R.drawable.e16), Integer.valueOf(R.drawable.e17), Integer.valueOf(R.drawable.e18), Integer.valueOf(R.drawable.e19), Integer.valueOf(R.drawable.e20), Integer.valueOf(R.drawable.e21), Integer.valueOf(R.drawable.e22), Integer.valueOf(R.drawable.e23), Integer.valueOf(R.drawable.e24), Integer.valueOf(R.drawable.e25), Integer.valueOf(R.drawable.e26), Integer.valueOf(R.drawable.restar2)};
    Integer[] icon1Images = new Integer[]{Integer.valueOf(R.drawable.a), Integer.valueOf(R.drawable.b), Integer.valueOf(R.drawable.c), Integer.valueOf(R.drawable.d), Integer.valueOf(R.drawable.e), Integer.valueOf(R.drawable.f), Integer.valueOf(R.drawable.g), Integer.valueOf(R.drawable.h), Integer.valueOf(R.drawable.i), Integer.valueOf(R.drawable.j), Integer.valueOf(R.drawable.k), Integer.valueOf(R.drawable.l), Integer.valueOf(R.drawable.m), Integer.valueOf(R.drawable.n), Integer.valueOf(R.drawable.o), Integer.valueOf(R.drawable.p), Integer.valueOf(R.drawable.q), Integer.valueOf(R.drawable.r), Integer.valueOf(R.drawable.s), Integer.valueOf(R.drawable.t), Integer.valueOf(R.drawable.u), Integer.valueOf(R.drawable.v), Integer.valueOf(R.drawable.w), Integer.valueOf(R.drawable.x), Integer.valueOf(R.drawable.y), Integer.valueOf(R.drawable.z), Integer.valueOf(R.drawable.resta)};
    Integer[] icon1Sound = new Integer[]{Integer.valueOf(R.raw.a), Integer.valueOf(R.raw.b), Integer.valueOf(R.raw.c), Integer.valueOf(R.raw.d), Integer.valueOf(R.raw.e), Integer.valueOf(R.raw.f), Integer.valueOf(R.raw.g), Integer.valueOf(R.raw.h), Integer.valueOf(R.raw.i), Integer.valueOf(R.raw.j), Integer.valueOf(R.raw.k), Integer.valueOf(R.raw.l), Integer.valueOf(R.raw.m), Integer.valueOf(R.raw.n), Integer.valueOf(R.raw.o), Integer.valueOf(R.raw.p), Integer.valueOf(R.raw.q), Integer.valueOf(R.raw.r), Integer.valueOf(R.raw.s), Integer.valueOf(R.raw.t), Integer.valueOf(R.raw.u), Integer.valueOf(R.raw.v), Integer.valueOf(R.raw.w), Integer.valueOf(R.raw.x), Integer.valueOf(R.raw.y), Integer.valueOf(R.raw.z), Integer.valueOf(R.raw.yahh_abc)};
    Integer[] icon2Images = new Integer[]{Integer.valueOf(R.drawable.n1), Integer.valueOf(R.drawable.n2), Integer.valueOf(R.drawable.n3), Integer.valueOf(R.drawable.n4), Integer.valueOf(R.drawable.n5), Integer.valueOf(R.drawable.n6), Integer.valueOf(R.drawable.n7), Integer.valueOf(R.drawable.n8), Integer.valueOf(R.drawable.n9), Integer.valueOf(R.drawable.n10), Integer.valueOf(R.drawable.resta)};
    Integer[] icon2Sound = new Integer[]{Integer.valueOf(R.raw.a1), Integer.valueOf(R.raw.a2), Integer.valueOf(R.raw.a3), Integer.valueOf(R.raw.a4), Integer.valueOf(R.raw.a5), Integer.valueOf(R.raw.a6), Integer.valueOf(R.raw.a7), Integer.valueOf(R.raw.a8), Integer.valueOf(R.raw.a9), Integer.valueOf(R.raw.a10), Integer.valueOf(R.raw.yahh_abc)};
    Integer[] icon3Images = new Integer[]{Integer.valueOf(R.drawable.f1), Integer.valueOf(R.drawable.f2), Integer.valueOf(R.drawable.f3), Integer.valueOf(R.drawable.f4), Integer.valueOf(R.drawable.f5), Integer.valueOf(R.drawable.f6), Integer.valueOf(R.drawable.f7), Integer.valueOf(R.drawable.f8), Integer.valueOf(R.drawable.f9), Integer.valueOf(R.drawable.f10), Integer.valueOf(R.drawable.resta)};
    Integer[] icon3Sound = new Integer[]{Integer.valueOf(R.raw.f1), Integer.valueOf(R.raw.f2), Integer.valueOf(R.raw.f3), Integer.valueOf(R.raw.f4), Integer.valueOf(R.raw.f5), Integer.valueOf(R.raw.f6), Integer.valueOf(R.raw.f7), Integer.valueOf(R.raw.f8), Integer.valueOf(R.raw.f9), Integer.valueOf(R.raw.f10), Integer.valueOf(R.raw.yahh_abc)};
    Integer[] icon4Images = new Integer[]{Integer.valueOf(R.drawable.an1), Integer.valueOf(R.drawable.an2), Integer.valueOf(R.drawable.an3), Integer.valueOf(R.drawable.an4), Integer.valueOf(R.drawable.an5), Integer.valueOf(R.drawable.an6), Integer.valueOf(R.drawable.an7), Integer.valueOf(R.drawable.an8), Integer.valueOf(R.drawable.an9), Integer.valueOf(R.drawable.an10), Integer.valueOf(R.drawable.an11), Integer.valueOf(R.drawable.an12), Integer.valueOf(R.drawable.an13), Integer.valueOf(R.drawable.an14), Integer.valueOf(R.drawable.an15), Integer.valueOf(R.drawable.an16), Integer.valueOf(R.drawable.restar_pn)};
    Integer[] icon4Sound = new Integer[]{Integer.valueOf(R.raw.an1), Integer.valueOf(R.raw.an2), Integer.valueOf(R.raw.an3), Integer.valueOf(R.raw.an4), Integer.valueOf(R.raw.an5), Integer.valueOf(R.raw.an6), Integer.valueOf(R.raw.an7), Integer.valueOf(R.raw.an8), Integer.valueOf(R.raw.an9), Integer.valueOf(R.raw.an10), Integer.valueOf(R.raw.an11), Integer.valueOf(R.raw.an12), Integer.valueOf(R.raw.an13), Integer.valueOf(R.raw.an14), Integer.valueOf(R.raw.an15), Integer.valueOf(R.raw.an16), Integer.valueOf(R.raw.yahh_abc)};
    Integer[] icon5Images = new Integer[]{Integer.valueOf(R.drawable.d1), Integer.valueOf(R.drawable.d2), Integer.valueOf(R.drawable.d3), Integer.valueOf(R.drawable.d4), Integer.valueOf(R.drawable.d5), Integer.valueOf(R.drawable.d6), Integer.valueOf(R.drawable.d7), Integer.valueOf(R.drawable.resta)};
    Integer[] icon5Sound = new Integer[]{Integer.valueOf(R.raw.d1), Integer.valueOf(R.raw.d2), Integer.valueOf(R.raw.d3), Integer.valueOf(R.raw.d4), Integer.valueOf(R.raw.d5), Integer.valueOf(R.raw.d6), Integer.valueOf(R.raw.d7), Integer.valueOf(R.raw.yahh_abc)};
    Integer[] icon6Images = new Integer[]{Integer.valueOf(R.drawable.s1), Integer.valueOf(R.drawable.s2), Integer.valueOf(R.drawable.s3), Integer.valueOf(R.drawable.s4), Integer.valueOf(R.drawable.s5), Integer.valueOf(R.drawable.s6), Integer.valueOf(R.drawable.s7), Integer.valueOf(R.drawable.s8), Integer.valueOf(R.drawable.s9), Integer.valueOf(R.drawable.s10), Integer.valueOf(R.drawable.s11), Integer.valueOf(R.drawable.s12), Integer.valueOf(R.drawable.restar_pn)};
    Integer[] icon6Sound = new Integer[]{Integer.valueOf(R.raw.m1), Integer.valueOf(R.raw.m2), Integer.valueOf(R.raw.m3), Integer.valueOf(R.raw.m4), Integer.valueOf(R.raw.m5), Integer.valueOf(R.raw.m6), Integer.valueOf(R.raw.m7), Integer.valueOf(R.raw.m8), Integer.valueOf(R.raw.m9), Integer.valueOf(R.raw.m10), Integer.valueOf(R.raw.m11), Integer.valueOf(R.raw.m12), Integer.valueOf(R.raw.yahh_abc)};
    Integer[] numberSounds = new Integer[]{Integer.valueOf(R.raw.a1), Integer.valueOf(R.raw.a2), Integer.valueOf(R.raw.a3), Integer.valueOf(R.raw.a4), Integer.valueOf(R.raw.a5), Integer.valueOf(R.raw.a6), Integer.valueOf(R.raw.a7), Integer.valueOf(R.raw.a8), Integer.valueOf(R.raw.a9), Integer.valueOf(R.raw.a10), Integer.valueOf(R.raw.yahh_abc)};
    Integer[] numberStroke = new Integer[]{Integer.valueOf(R.drawable.en1), Integer.valueOf(R.drawable.en2), Integer.valueOf(R.drawable.en3), Integer.valueOf(R.drawable.en4), Integer.valueOf(R.drawable.en5), Integer.valueOf(R.drawable.en6), Integer.valueOf(R.drawable.en7), Integer.valueOf(R.drawable.en8), Integer.valueOf(R.drawable.en9), Integer.valueOf(R.drawable.en10), Integer.valueOf(R.drawable.restar2)};

    public ResourcePool() {
    }
}